default:
  image: node:21.7-alpine3.19

# variables:
#   VERCEL_ORG_ID: $VERCEL_ORG_ID

# .base_rules: &base_rules
#   only:
#     - master

stages:
  - install
  - test
  # - build
  # - deploy

Install:
  # <<: *base_rules
  stage: install
  needs: []
  script:
    - npm ci --cache .npm --prefer-offline --progress=false --no-audit
    - npm i jest --save-dev --quiet
    - npm run build

Test:
  stage: test
  needs: []
  script:
    - npm test

# Build:
#   <<: *base_rules
#   stage: build
#   needs: []
#   script:
#     - npm run build
#   cache:
#     paths:
#       - .next/

# Deploy:
#   stage: deploy
#   environment:
#     name: production
#   variables:
#     VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID
#   script:
#     - npm i -g vercel
#     - vercel --confirm -t $VERCEL_TOKEN --prod
#   only:
#     - master
